spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/customer?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: create
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      fetch-registry: true
      register-with-eureka: true
      enabled: false

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans