spring:
  application:
    name: customer
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: default
  zipkin:
    base-url: http://127.0.0.1:9411/
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 8081