spring:
  application:
    name: notification
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: default
  rabbitmq:
    addresses: localhost:5672
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

server:
  port: 8083

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key